version: '3'
services:
  myapp:

    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3000:3000"
    networks:
      - test
networks:
  test:
    driver: bridge
    # external: true
